# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks
# To update to all latest tagged versions run:
#     pre-commit autoupdate
# TODO: write dependencies install instructions and put in each of
#       my pre-commit repos. Decide where to put for others
repos:
  - repo: git://github.com/devops-workflow/pre-commit-terraform
    # Requires: terraform, terraform-docs
    rev: v1.7.3
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      # - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-yaml
      # TODO: test these
      # check-json
      # pretty-format-json
      # detect-aws-credentials
      # detect-private-key
  #- repo: https://github.com/jumanjihouse/pre-commit-hooks
  #  # Requires: shellcheck, shfmt
  #  rev: 1.8.0
  #  hooks:
  #    - id: shellcheck
  #    - id: shfmt
  #- repo: git://github.com/detailyang/pre-commit-shell
  #  # Requires: shellcheck
  #  rev: 1.0.2
  #  hooks:
  #    - id: shell-lint
# TODO:
# add bashate shell code style https://github.com/openstack-dev/bashate
# gitlint https://github.com/jorisroovers/gitlint
# Create new repo and hook for markdown linters
